yaminabe.command.version.print=<green>Yaminabe <aqua><version>
yaminabe.command.reload.start=<gray>Yaminabe を再読み込みしています...
yaminabe.command.reload.config-reloaded=<green>設定ファイルを再読み込みしました。
yaminabe.command.reload.config-failed=<red>設定ファイルの再読み込みに失敗しました。詳細はコンソールを確認してください。
yaminabe.command.reload.language-reloaded=<green>言語ファイルを再読み込みしました。
yaminabe.command.reload.language-failed=<red>言語ファイルの再読み込みに失敗しました。詳細はコンソールを確認してください。
