yaminabe.command.version.print=<green>Yaminabe <aqua><version>
yaminabe.command.disposal.title=ゴミ箱
yaminabe.command.disposal.opening=<gray>ゴミ箱を開いています...
yaminabe.command.disposal.player-only=<red>ゲーム内のプレイヤーのみ </red><aqua><command></aqua><red> を使用できます。
yaminabe.command.hat.fail=<red>アイテムをかぶるには、アイテムを手に持つ必要があります。
yaminabe.command.hat.prevented=<red>このアイテムは被れません。
yaminabe.command.hat.curse=<red>束縛の呪いが付与されたアイテムは外せません。
yaminabe.command.hat.empty=<red>あなたは何も被っていません。
yaminabe.command.hat.placed=<gray>アイテムを被りました。
yaminabe.command.hat.removed=<gray>アイテムを外しました。
yaminabe.command.hat.player-only=<red>ゲーム内のプレイヤーのみ </red><aqua><command></aqua><red> を使用できます。
yaminabe.command.item.given=<aqua><item></aqua><gray> が </gray><aqua><amount>個</aqua><gray> インベントリに追加されました。
yaminabe.command.item.player-only=<red>ゲーム内のプレイヤーのみ </red><aqua><command></aqua><red> を使用できます。
yaminabe.command.itemname.no-item=<red>名前を変更するにはアイテムを手に持つ必要があります。
yaminabe.command.itemname.cleared=<gray>手に持っているアイテムの名前をクリアしました。
yaminabe.command.itemname.renamed=<gray>手に持っているアイテムの名前を </gray><aqua><name></aqua><gray> に変更しました。
yaminabe.command.itemname.prevented=<red>あなたは </red><aqua><item></aqua><red> の名前を変更する権限がありません。
yaminabe.command.itemname.too-long=<red>名前は </red><aqua><limit>文字</aqua><red> 以内である必要があります。
yaminabe.command.itemname.player-only=<red>ゲーム内のプレイヤーのみ </red><aqua><command></aqua><red> を使用できます。
