yaminabe.command.version.print=<green>Yaminabe <aqua><version>
yaminabe.command.disposal.title=ゴミ箱
yaminabe.command.disposal.opening=<gray>ゴミ箱を開いています...
yaminabe.command.disposal.player-only=<red>ゲーム内のプレイヤーのみ </red><aqua><command></aqua><red> を使用できます。
yaminabe.command.hat.fail=<red>アイテムをかぶるには、アイテムを手に持つ必要があります。
yaminabe.command.hat.prevented=<red>このアイテムは被れません。
yaminabe.command.hat.curse=<red>束縛の呪いが付与されたアイテムは外せません。
yaminabe.command.hat.empty=<red>あなたは何も被っていません。
yaminabe.command.hat.placed=<gray>アイテムを被りました。
yaminabe.command.hat.removed=<gray>アイテムを外しました。
yaminabe.command.hat.player-only=<red>ゲーム内のプレイヤーのみ </red><aqua><command></aqua><red> を使用できます。
yaminabe.command.item.given=<aqua><item></aqua><gray> が </gray><aqua><amount>個</aqua><gray> インベントリに追加されました。
yaminabe.command.item.player-only=<red>ゲーム内のプレイヤーのみ </red><aqua><command></aqua><red> を使用できます。
yaminabe.command.itemname.no-item=<red>名前を変更するにはアイテムを手に持つ必要があります。
yaminabe.command.itemname.cleared=<gray>手に持っているアイテムの名前をクリアしました。
yaminabe.command.itemname.renamed=<gray>手に持っているアイテムの名前を </gray><aqua><name></aqua><gray> に変更しました。
yaminabe.command.itemname.prevented=<red>あなたは </red><aqua><item></aqua><red> の名前を変更する権限がありません。
yaminabe.command.itemname.too-long=<red>名前は </red><aqua><limit>文字</aqua><red> 以内である必要があります。
yaminabe.command.itemname.player-only=<red>ゲーム内のプレイヤーのみ </red><aqua><command></aqua><red> を使用できます。
yaminabe.command.itemlore.no-item=<red>説明文を編集するにはアイテムを手に持つ必要があります。
yaminabe.command.itemlore.no-lore=<red>手に持っているアイテムには説明文がありません。
yaminabe.command.itemlore.no-line=<red>手に持っているアイテムの説明文に </red><aqua><line>行目</aqua><red> はありません。
yaminabe.command.itemlore.line-out-of-range=<red>手に持っているアイテムの説明文に挿入できるのは </red><aqua><max>行目</aqua><red> までです。
yaminabe.command.itemlore.added=<gray>手に持っているアイテムの説明文に </gray><aqua><line></aqua><gray> を追加しました。
yaminabe.command.itemlore.set=<gray>手に持っているアイテムの説明文の </gray><aqua><number>行目</aqua><gray> を </gray><aqua><line></aqua><gray> に変更しました。
yaminabe.command.itemlore.inserted=<gray>手に持っているアイテムの説明文の </gray><aqua><number>行目</aqua><gray> に </gray><aqua><line></aqua><gray> を挿入しました。
yaminabe.command.itemlore.removed=<gray>手に持っているアイテムの説明文から </gray><aqua><number>行目</aqua><gray> を削除しました。
yaminabe.command.itemlore.cleared=<gray>手に持っているアイテムの説明文をクリアしました。
yaminabe.command.itemlore.prevented=<red>あなたは </red><aqua><item></aqua><red> の説明文を編集する権限がありません。
yaminabe.command.itemlore.too-long=<red>各行は </red><aqua><limit>文字</aqua><red> 以内である必要があります。
yaminabe.command.itemlore.too-many-lines=<red>説明文は </red><aqua><limit>行</aqua><red> 以内である必要があります。
yaminabe.command.itemlore.player-only=<red>ゲーム内のプレイヤーのみ </red><aqua><command></aqua><red> を使用できます。
yaminabe.command.sign.player-only=<red>座標を指定しない場合、ゲーム内のプレイヤーのみ </red><aqua><command></aqua><red> を使用できます。
yaminabe.command.sign.not-looked-at=<red>看板を見ている必要があります。
yaminabe.command.sign.not-found=<red><aqua><x> <y> <z></aqua><red> に看板はありません。
yaminabe.command.sign.chunk-not-loaded=<red><aqua><x> <y> <z></aqua><red> のチャンクは読み込まれていません。
yaminabe.command.sign.is-waxed=<red>あなたは蜜蝋が塗られた看板を編集する権限がありません。
yaminabe.command.sign.edit-prevented=<red>この看板の編集は許可されませんでした。
yaminabe.command.sign.too-long=<red>各行は </red><aqua><limit>文字</aqua><red> 以内である必要があります。
yaminabe.command.sign.last-line-not-empty=<red>行を挿入するには </red><aqua><number>行目</aqua><red> が空である必要があります。
yaminabe.command.sign.set=<gray>看板の </gray><aqua><number>行目</aqua><gray> を </gray><aqua><line></aqua><gray> に変更しました。
yaminabe.command.sign.inserted=<gray>看板の </gray><aqua><number>行目</aqua><gray> に </gray><aqua><line></aqua><gray> を挿入しました。
yaminabe.command.sign.removed=<gray>看板から </gray><aqua><number>行目</aqua><gray> を削除しました。
yaminabe.command.sign.cleared=<gray>看板をクリアしました。
yaminabe.command.sign.cleared-line=<gray>看板の </gray><aqua><number>行目</aqua><gray> をクリアしました。
yaminabe.command.sign.already-empty=<red>看板には何も書かれていません。
yaminabe.command.sign.line-already-empty=<red>看板の </red><aqua><number>行目</aqua><red> には何も書かれていません。
yaminabe.command.sign.glowing-enabled=<gray>看板の文字が光るようになりました。
yaminabe.command.sign.glowing-disabled=<gray>看板の文字が光らなくなりました。
yaminabe.command.sign.color-set=<gray>看板の文字色を </gray><aqua><color></aqua><gray> に変更しました。
yaminabe.command.sign.invalid-color=<red><aqua><color></aqua><red> は染料の色ではありません。
yaminabe.command.sign.waxed-enabled=<gray>看板に蜜蝋を塗りました。
yaminabe.command.sign.waxed-disabled=<gray>看板の蜜蝋を剥がしました。
yaminabe.command.skull.given=<aqua><owner></aqua><gray> の頭がインベントリに追加されました。
yaminabe.command.skull.invalid-name=<red>プレイヤー名を指定してください。
yaminabe.command.skull.invalid-owner=<red>プレイヤー名、テクスチャハッシュ、またはテクスチャ値を指定してください。
yaminabe.command.skull.online-prevented=<red>あなたは他のプレイヤーの頭を入手する権限がありません。
yaminabe.command.skull.offline-prevented=<red>あなたはオンラインでないプレイヤーの頭を入手する権限がありません。
yaminabe.command.skull.texture-prevented=<red>あなたはテクスチャを指定して頭を入手する権限がありません。
yaminabe.command.skull.player-only=<red>ゲーム内のプレイヤーのみ </red><aqua><command></aqua><red> を使用できます。
yaminabe.command.workbench.player-only=<red>ゲーム内のプレイヤーのみ </red><aqua><command></aqua><red> を使用できます。
yaminabe.command.anvil.player-only=<red>ゲーム内のプレイヤーのみ </red><aqua><command></aqua><red> を使用できます。
yaminabe.command.cartographytable.player-only=<red>ゲーム内のプレイヤーのみ </red><aqua><command></aqua><red> を使用できます。
yaminabe.command.grindstone.player-only=<red>ゲーム内のプレイヤーのみ </red><aqua><command></aqua><red> を使用できます。
yaminabe.command.loom.player-only=<red>ゲーム内のプレイヤーのみ </red><aqua><command></aqua><red> を使用できます。
yaminabe.command.smithingtable.player-only=<red>ゲーム内のプレイヤーのみ </red><aqua><command></aqua><red> を使用できます。
yaminabe.command.stonecutter.player-only=<red>ゲーム内のプレイヤーのみ </red><aqua><command></aqua><red> を使用できます。
