yaminabe.command.version.print=<green>Yaminabe <aqua><version>
yaminabe.command.disposal.title=ゴミ箱
yaminabe.command.disposal.opening=<gray>ゴミ箱を開いています...
yaminabe.command.disposal.player-only=<red>ゲーム内のプレイヤーのみ </red><aqua><command></aqua><red> を使用できます。
