# Shared commands
yaminabe.command.version.print=<green>Yaminabe <aqua><version>
yaminabe.command.reload.start=<gray>Yaminabe を再読み込みしています...
yaminabe.command.reload.config-reloaded=<green>設定ファイルを再読み込みしました。
yaminabe.command.reload.config-failed=<red>設定ファイルの再読み込みに失敗しました。詳細はコンソールを確認してください。
yaminabe.command.reload.language-reloaded=<green>言語ファイルを再読み込みしました。
yaminabe.command.reload.language-failed=<red>言語ファイルの再読み込みに失敗しました。詳細はコンソールを確認してください。

# Restart commands
yaminabe.command.autorestart.restart-scheduled=<gray>再起動を <aqua><time></aqua><gray> に予約しました。
yaminabe.command.autorestart.stop-scheduled=<gray>シャットダウンを <aqua><time></aqua><gray> に予約しました。
yaminabe.command.autorestart.restart-immediate=<gray>再起動を直ちに予約しました。
yaminabe.command.autorestart.stop-immediate=<gray>シャットダウンを直ちに予約しました。
yaminabe.command.autorestart.restart-cancelled=<gray><aqua><time></aqua><gray> に予約されていた再起動をキャンセルしました。
yaminabe.command.autorestart.stop-cancelled=<gray><aqua><time></aqua><gray> に予約されていたシャットダウンをキャンセルしました。
yaminabe.command.autorestart.automatic-restart-scheduled=<gray>次の自動再起動は <aqua><time></aqua><gray> に予約されています。
yaminabe.command.autorestart.nothing-to-cancel=<red>キャンセルできる再起動またはシャットダウンの予約はありません。
yaminabe.command.autorestart.invalid-duration=<red>期間の指定が正しくありません: <aqua><input></aqua><red>。
yaminabe.command.autorestart.invalid-date-time=<red>日時の指定が正しくありません: <aqua><input></aqua><red>。
yaminabe.command.autorestart.schedule-failed=<red>予約を有効にできませんでした。

# Restart execution
yaminabe.restart.restart-kick=<red>サーバーを再起動しています。</red>
yaminabe.restart.stop-kick=<red>サーバーをシャットダウンしています。</red>
yaminabe.restart.restart-kick-with-reason=<red>サーバーを再起動しています: <reason></red>
yaminabe.restart.stop-kick-with-reason=<red>サーバーをシャットダウンしています: <reason></red>

# Restart countdown
yaminabe.restart.countdown-restart=<red>サーバーは <aqua><seconds></aqua><red> 秒後に再起動します。</red>
yaminabe.restart.countdown-restart-with-reason=<red>サーバーは <aqua><seconds></aqua><red> 秒後に再起動します: <reason></red>
yaminabe.restart.countdown-stop=<red>サーバーは <aqua><seconds></aqua><red> 秒後にシャットダウンします。</red>
yaminabe.restart.countdown-stop-with-reason=<red>サーバーは <aqua><seconds></aqua><red> 秒後にシャットダウンします: <reason></red>
yaminabe.restart.boss-bar-restart=<red>サーバー再起動まで <aqua><seconds></aqua><red> 秒</red>
yaminabe.restart.boss-bar-restart-with-reason=<red>サーバー再起動まで <aqua><seconds></aqua><red> 秒: <reason></red>
yaminabe.restart.boss-bar-stop=<red>サーバーシャットダウンまで <aqua><seconds></aqua><red> 秒</red>
yaminabe.restart.boss-bar-stop-with-reason=<red>サーバーシャットダウンまで <aqua><seconds></aqua><red> 秒: <reason></red>
