name: Build
on: [ push, pull_request ]

jobs:
  build:
    uses: okocraft/workflows/.github/workflows/gradle.yml@v1
    with:
      java-version: '21'
      package-name: Yaminabe-Build-${{ github.run_number }}
      artifact-directory: "./build/libs"
      upload-test-results: true
