name: Patch EssentialsX

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Patch latest EssentialsX dev build
        run: python3 scripts/patch-essentialsx.py

      - name: Upload patched EssentialsX
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          path: build/essentialsx/*-patched.jar
          if-no-files-found: error
